apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-safe
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safe
  template:
    metadata:
      labels:
        app: safe
    spec:
      containers:
        - name: app
          image: nginx:alpine
          securityContext:
            privileged: false
      initContainers:
        - name: init
          image: busybox
          command: ["echo", "init safe"]
          securityContext:
            privileged: false
      hostNetwork: false
